FROM ubuntu:bionic

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    python-pkg-resources \
    git \
    systemd \
 && rm -rf /var/lib/apt/lists/*

RUN pip2 install --upgrade  pip setuptools wheel && pip2 install ansible && mkdir -p /etc/ansible/

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]